### ISSUE TITLE
Bug when sending an array as first and only parameter

### ISSUE THREAD

**Issue by Adidi** [fguillot/JsonRPC#11]
If i have a function i expose in my jsonrpc server that gets array as the only parmeter:
```php
function getTemplates(array $templates){
   foreach($templates as $template){
      //do something....
   }
}
```
When calling it from the client ```$client->getTemplates([1,2,3])``` I'll get ```InvalidArgumentException``` because of lines 118-120 in Client.php:
```php
if (count($params) === 1 && is_array($params[0])) {
            $params = $params[0];
       }
```
You convert the first array param to be the all params.
What is the purpose of that? 

Regards

**Comment by fguillot** [comment]
Use `$client->getTemplates([[1,2,3]])` or set `$client->named_arguments = false;`.
