### ISSUE TITLE
This issue Class 'Client' not found in

### ISSUE THREAD

**Issue by deathquin** [fguillot/JsonRPC#13]
I using JsonRPC
But The following problems occurred.

server code.

<?php
  require 'vendor/autoload.php';

  //use JsonRPC\Server;

  require_once 'JsonRPC/Server.php';
  
  $server = new Server;

  // Procedures registration

  $server->register('addition', function ($a, $b) 
  {
      return $a + $b;
  });

  $server->register('random', function ($start, $end) 
  {
      return mt_rand($start, $end);
  });

  // Return the response to the client
  echo $server->execute();
?>

client code

<?php
  require 'vendor/autoload.php';
  require_once 'JsonRPC/Client.php';
  
  $target = 'http://'.$_SERVER['SERVER_NAME'].dirname($_SERVER['SCRIPT_NAME']).'/server.php';
  $client = new Client($target);

  $result = $client->execute('addition', [3, 5]);

  var_dump($result);
?>

This Issue :
Fatal error: Class 'Client' not found in C:\nginx-1.6.2\nginx-1.6.2\html\JsonRPC-master\src\client.php on line 6

I want to fix this problem
How can I correct this?

And use the local server.

Thank you :)

**Comment by fguillot** [comment]
You forgot the namespace `JsonRPC\Client(...` or add `use JsonRPC\Client;`
