### ISSUE TITLE
the server always return null

### ISSUE THREAD

**Issue by islam-muhamed** [fguillot/JsonRPC#14]
my server side code
<?php
require 'JsonRPC/Server.php';
use JsonRPC\Server;

$server = new Server;

// Procedures registration

$server->register('addition', function ($a, $b) {
    return $a + $b;
});

$server->register('random', function ($start, $end) {
    return mt_rand($start, $end);
});

// Return the response to the client
echo $server->execute();

/*******************************************************************************/
and the client side code

<?php
require 'JsonRPC/Client.php';
use JsonRPC\Client;

$client = new Client('http://localhost/server.php');
$result = $client->execute('random', ['end' => 10, 'start' => 1]);
var_dump($result);

but it always print NULL 

i didn't see any problem here i just copy the example you provide 
could you help me

**Comment by islam-muhamed** [comment]
i print $client object and here is the result


JsonRPC\Client Object
(
    [url:JsonRPC\Client:private] => http://localhost/home.php
    [timeout:JsonRPC\Client:private] => 5
    [username:JsonRPC\Client:private] => 
    [password:JsonRPC\Client:private] => 
    [is_batch] => 
    [batch] => Array
        (
        )

    [debug] => 
    [headers:JsonRPC\Client:private] => Array
        (
            [0] => Connection: close
            [1] => Content-Type: application/json
            [2] => Accept: application/json
        )

    [ssl_verify_peer] => 1
)

**Comment by fguillot** [comment]
If you enable the debug output (`$client->debug = true;`) you will be able to see the request and the response from the server and then find where the problem come from. 

The debug information are sent with the function `error_log()`: https://github.com/fguillot/JsonRPC/blob/master/src/JsonRPC/Client.php#L313-L316

**Comment by cyking** [comment]
I don't know if this is relate, but on some servers I tested curl seems to be causing a segment fault.  which makes it appear that it is returning nothing.

I haven't been able to resolve this.

Check your nginx or apache2 error log for something like this:
```log
2015/03/13 00:48:56 [alert] 5395#0: worker process 5396 exited on signal 11
```

http://stackoverflow.com/questions/25397142/curl-to-https-stop-working-with-nginx-php-fpm
