### ISSUE TITLE
add option to use urlfetch in `Client.php`

### ISSUE THREAD

**Issue by cyking** [fguillot/JsonRPC#15]
PHP-Curl still has bug where on some installations causes a segment fault.

http://stackoverflow.com/questions/25397142/curl-to-https-stop-working-with-nginx-php-fpm

Some JSON-RPC services refuse access from curl clients. Google suggested using urlfetch

http://stackoverflow.com/questions/18114206/replacing-curl-with-urlfetch-in-php

**Comment by cyking** [comment]
i'm really more use to gitlab than github.  I made some changes I think you may like.    

please checkout:

 commit: https://github.com/cyking/JsonRPC/commit/20e14e627c031081c97e6eeb80930508c80f6fc5

branch:  https://github.com/cyking/JsonRPC/tree/cyking_add_option_to_use_urlfetch

**Comment by fguillot** [comment]
The master branch use stream context now instead of curl, so there is no dependencies.
