### ISSUE TITLE
composer install requiring @dev stability

### ISSUE THREAD

**Issue by thiagof** [fguillot/JsonRPC#23]
Composer finds the package as "unstable". That seems to mean the package is lacking tags/release.
Alias also could be used.

Does you experience the problem?

composer.json that would not install:
```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "require": {
        "fguillot/json-rpc": "dev-master"
    }
}
```

**Comment by fguillot** [comment]
There is a couple of tags now, you can use the version number in your composer file.
