### ISSUE TITLE
The way to issue a custom error response

### ISSUE THREAD

**Issue by kawa-** [fguillot/JsonRPC#3]
Hi. This project is really amazing and I have a question. 
Like this post (http://stackoverflow.com/questions/18321144/zf2-json-rpc-server-how-to-return-custom-error), I'd like to write a custom error response.
How can I make it?

**Comment by cyking** [comment]
@kawa- checkout https://github.com/cyking/JsonRPC/issues/4

**Comment by fguillot** [comment]
See https://github.com/fguillot/JsonRPC#exceptions
