### ISSUE TITLE
How can we make call with javascripts ?

### ISSUE THREAD

**Issue by tejastank** [fguillot/JsonRPC#31]
Hello,

We like to use this, loved its features.

Like to know how can I make calls with JavaScript ?

**Comment by EpocDotFr** [comment]
You can use this [jQuery plugin](https://github.com/datagraph/jquery-jsonrpc).

Note that if you make calls to another domain than the one who's initiating the call, you'll need to activate [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) support on the JSON-RPC server.

**Comment by BlueTeck** [comment]
If you are using angularjs, you could make the call with $http.post without any plugin. 

```
var user = 'test';
var password = '123';
var request = '{"jsonrpc": "2.0", "method": "getAllProjects", "id": 1}';
var endpoint = 'http://adress_of_endpoint';
$.ajax({
                    url: endpoint,
                    type: 'POST',
                    dataType: 'json',
                    crossDomain: true,
                    data: request,
                    beforeSend: function (xhr) {
                        var auth = Base64.encode(user + ':' + password);
                        xhr.setRequestHeader("Authorization", "Basic " + auth);
                    },
                    success: function (data) {
                        var result = data.result;
                    },
                    error: function (data) {
                        
                    }
                });
```

Or in Jquery with $.ajax without a plugin:
```
var user = 'test';
var password = '123';
var request = '{"jsonrpc": "2.0", "method": "getAllProjects", "id": 1}';
var auth = Base64.encode(user + ':' + password);
    var config = {
      headers: {
        'Authorization': 'Basic ' + auth
      }
    };
$http.post('url', request, config);
```

**Comment by tejastank** [comment]
Thanks for all to answer. I will check both code.

**Comment by BlueTeck** [comment]
I have uploaded my little testscript to Github, you can check it out here: http://github.com/BlueTeck/js_jsonrpc_tester

![image](https://cloud.githubusercontent.com/assets/1961634/9963476/be986d8e-5e2b-11e5-83cd-43a7e6098a8f.png)

**Comment by fabdelgado** [comment]
Hi, with this code fail in angularjs.

Response:
Error is: XMLHttpRequest cannot load http://192.10.10.16/jsonrpc.php. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://boss:8888' is therefore not allowed access.
app.js:29 null


That could be happening?


```
var app = angular.module('app', ['base64']);

app.controller("DashCtrl", ["$scope", "$http", "$interval",'$base64',
	function($scope,$http,$interval,$base64){

    var user = 'jsonrpc';
    var password = '123';
    var request = '{"jsonrpc": "2.0", "method": "getAllProjects", "id": 1}';
    var auth = $base64.encode(user + ':' + password);
// tenes documentacion del puto kanban ese?
  		var req = {
  			method: 'GET',
        crossDomain: true,
        data: request,
  			url: 'http://192.168.10.186/jsonrpc.php',
  			headers: {
  				'Content-Type': ' application/json',
  				'X-API-Auth': '123',
          'Authorization': 'Basic ' + auth
  			}
  		};

      $scope.reload = function () {
        $http(req)
          .success(function(data, status) {
            console.log(data);
          })
          .error(function(data, status) {
            console.log(data);
          })
      };

      	$scope.reload();

}]);

```

**Comment by BlueTeck** [comment]
You are trying to access another doamin via ajax, that is not alowed by default.

See "Access-Control-Allow-Origin" or "CORS" on Google.

I you are testing/developing with Google Chrome, this plugin helps: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog

**Comment by fabdelgado** [comment]
Thankyou @BlueTeck
