### ISSUE TITLE
Client: add a way to modify the request sent to the server

### ISSUE THREAD

**Issue by sloonz** [fguillot/JsonRPC#38]
The third argument allow us to modify headers sent to the server ; however, this does not allow the developer to modify the headers on a per-call basis.

The server I’m trying to contact require to sign every request with an HMAC ; this means that the value of the header will depend on the payload.

A cheap way to achieve with would be to make `getContext` protected. A sightly better one would be to add a protected method `getHeaders($payload)` which would just be `return $this->headers` by default, but overrideable by a subclass. BTW, although it is not my situation, the same problem may arise with respect to the URL (for example, in order to add a ?hmac-tag=...).

**Comment by fguillot** [comment]
You can use a callback to add a new HTTP header before the request is made.

See https://github.com/fguillot/JsonRPC#callback-before-client-request

**Comment by sloonz** [comment]
Looks like exactly what I needs ; thanks :)
