### ISSUE TITLE
Often getting ConnectionFailureException

### ISSUE THREAD

**Issue by Phyks** [fguillot/JsonRPC#39]
Hi,

I am often getting `ConnectionFailureException` with this lib and `miniflux`, however I am not sure which one is to blame. Most of the time, I can just reload the page and it works.

```
Fatal error: Uncaught JsonRPC\ConnectionFailureException: Unable to establish a connection in /srv/http/miniflux_api/vendor/fguillot/json-rpc/src/JsonRPC/Client.php:319 Stack trace: #0 /srv/http/miniflux_api/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(201): JsonRPC\Client->doRequest(Array) #1 /srv/http/miniflux_api/index.php(36): JsonRPC\Client->execute('feed.update', Array) #2 {main} thrown in /srv/http/miniflux_api/vendor/fguillot/json-rpc/src/JsonRPC/Client.php on line 319
```

It is coming from [this line](https://github.com/Phyks/miniflux_api/blob/master/index.php#L36) of my (very simple) script based on examples in Miniflux doc, but I cannot find what is going wrong with either Miniflux or this lib.

Thanks

**Comment by fguillot** [comment]
Maybe it's coming from your web server, too busy or too slow to handle too many connections? I don't know, it's hard to say.

**Comment by Phyks** [comment]
I am making requests on a Miniflux instance. Both Miniflux and my script using JSONRPC runs on the same computer (which is actually my laptop). So there should not be communication problems between the two of them, since it's basically localhost.

I use the standard Nginx + PHP-FPM setup, and I did not find any evidence of the webserver being too slow in the logs.

**Comment by Phyks** [comment]
Ok, found a bit more about it, and I would tend to think this is due to Miniflux being synchronous in the update call, and then getting a timeout if a feed is not reachable.

**Comment by fguillot** [comment]
The default timeout is now 5 seconds in the client, if the processing is too slow, you will have an exception.
