### ISSUE TITLE
All Exceptions relayed to client

### ISSUE THREAD

**Issue by Echron** [fguillot/JsonRPC#45]
All exceptions thrown are now relayed to client, the server property "$this->exceptons" is ignored when executing the server. This part of the code is gone after the refactoring commit (27a1a4de37f20ee0fd3551168a1da371fa3a0242)

![image](https://cloud.githubusercontent.com/assets/2070180/15215490/1df9449c-1853-11e6-88b1-ba81eb9df1ae.png)

In the execute method every exception is catched and send to the client with the response. 
Maybe it's an idea to make it possible to blacklist relayed exceptions so you can have Exceptions who are NOT relayed to the client.

**Comment by fguillot** [comment]
Should be fixed since the time...
