### ISSUE TITLE
Update visibility inside JsonRPC/Server class

### ISSUE THREAD

**Issue by dlevel** [fguillot/JsonRPC#46]
Hi there,

I would like to make a PR in order to change the visibility of some elements in this class.
In fact, it is really difficult to extend the class in order to update the way that the query is parsed.

Furthermore I would like to make the properties protected. I understand that your goal was to protected the class' attributes but I am not sure it is necessary to not be able to manipulate it in a sub class.

Does it seams good to you? If you are ok with this approach I can make the PR.

**Comment by fguillot** [comment]
no problem

**Comment by rparpa** [comment]
Hello all.

@dlevel and I updated Server class altogether. You can find the PR below:
https://github.com/fguillot/JsonRPC/pull/47

**Comment by fguillot** [comment]
I merged your PR, if you see something else to improve, feel free to send a PR.
