### ISSUE TITLE
How to return errors?

### ISSUE THREAD

**Issue by Fayozjon** [fguillot/JsonRPC#55]
Hi there!
Please provide code for returning errors with custom codes
For example -31319

**Comment by Fayozjon** [comment]
How to return this like exceptions ?


`  "error" : {
        "code" : -31050,
        "message" : {
            "ru" : "Номер телефона не найден",
            "uz" : "Raqam ro'yhatda yo'q",
            "en" : "Phone number not found"
        },
        "data" : "phone"
    },
    "result" : null,
    "id" : 2032`

**Comment by Elycin** [comment]
bump, stuck going through the code to try to solve my error.
InvalidJsonRpcFormatException in ResponseParser.php line 129: Invalid Request: Params must be an array

Impossible to debug with the library.

**Comment by zored** [comment]
`throw new \JsonRPC\Exception\ResponseException($message, $code, $previousException, $data);`
