### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by xVGERx** [fguillot/JsonRPC#8]
I've been trying to create the following request without any luck:
```Json  
 {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "call.search",
        "params": [
            "acc",
            srh: {
                "user"
            }
        ]
    }
```
Is this even possible using the client class, what do you think?

**Comment by fguillot** [comment]
It's not a valid JSON.

**Comment by xVGERx** [comment]
Thanks for responding, I found out later that the json was an error in documentation for API that I was trying to connect with.
